# Generated by Django 3.2.8 on 2021-10-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('pic', models.ImageField(upload_to='project-img/')),
                ('description', models.CharField(max_length=200)),
                ('github', models.URLField(max_length=500)),
                ('webapp', models.URLField(max_length=500)),
            ],
        ),
    ]
