# Generated by Django 3.2.8 on 2021-10-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='github',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='webapp',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
